[[plugins]]  # プラグインマネージャ
repo = 'Shougo/dein.vim'

[[plugins]]  # 非同期ライブラリ
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]  # ファイラー
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  let g:NERDTreeShowHidden = 0
'''

[[plugins]]
repo = 'toyamarinyon/vim-swift'

[[plugins]]  # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]  # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]  # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]  # カラースキーマ
repo = 'satosystems/desert.vim'
hook_add = '''
  syntax on
  set background=light
  let g:solarized_termcolors=256
  if has('nvim')
    au MyAutoCmd VimEnter * nested colorscheme desert
  else
    colorscheme desert
  endif
'''

[[plugins]]  # 日本語ヘルプ
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  " see: http://qiita.com/uplus_e10/items/2a75fbe3d80063eb9c18
  let g:quickrun_config = {
  \    "_" : {
  \        'runner': 'vimproc',
  \        'runner/vimproc/updatetime': 60,
  \        'outputter': 'error',
  \        'outputter/error/success': 'buffer',
  \        'outputter/error/error': 'quickfix',
  \        'outputter/buffer/split': ':rightbelow 8sp',
  \        'outputter/buffer/close_on_empty': 1,
  \    },
  \   'haskell': { 'type': 'haskell/stack' },
  \   'haskell/stack': {
  \       'command': 'stack',
  \       'exec': '%c %o %s %a',
  \       'cmdopt': 'runghc',
  \   },
  \}
  " \r で quickfix を閉じて、保存してから quickrun を実行する
  " FIXME: nvim だと quickfix が cclose で閉じてくれない
  let g:quickrun_no_default_key_mappings = 1
  nnoremap \r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
  xnoremap \r :<C-U>cclose<CR>:write<CR>gv:QuickRun -mode v<CR>
  " <C-c> で quickrun を停止
  nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''

[[plugins]]  # Haskell の補完
repo = 'eagletmt/neco-ghc'

[[plugins]]  # ghc-mod
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'eagletmt/unite-haddock'

[[plugins]]
repo = 'dag/vim2hs'

[[plugins]]
repo = 'ujihisa/unite-haskellimport'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]  # 汎用コメントアウト
repo = 'tomtom/tcomment_vim'

[[plugins]]  # Markdown プラグイン
repo = 'plasticboy/vim-markdown'

[[plugins]]  # Markdown プレビュー
repo = 'kannokanno/previm'

[[plugins]]  # ブラウザ自動同期
repo = 'tyru/open-browser.vim'

[[plugins]]  # swig syntax
repo = 'SpaceVim/vim-swig'
on_ft = 'i'

# Raspberry Pi 環境で非常に時間がかかるためコメントアウト
#[[plugins]]  # My sample
#repo = 'satosystems/neovim-plugin-hello-haskell'
#build = 'stack build'

