[[plugins]]  # プラグインマネージャ
repo = 'Shougo/dein.vim'

[[plugins]]  # 非同期ライブラリ
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]  # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]  # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]  # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]  # カラースキーマ
repo = 'satosystems/newspaper.vim'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme newspaper
'''

[[plugins]]  # Haskell の補完
repo = 'eagletmt/neco-ghc'

[[plugins]]  # ghc-mod
repo = 'eagletmt/ghcmod-vim'

[[plugins]]  # My sample
repo = 'satosystems/neovim-plugin-hello-haskell'
build = 'stack build'

